### ISSUE TITLE
Wrong download url for node-webkit

### ISSUE THREAD

**Issue by shripathee** [mllrsohn/grunt-nw-builder#138]
![screen shot 2015-07-07 at 11 38 27 am](https://cloud.githubusercontent.com/assets/1854248/8539766/f1651550-249c-11e5-9306-d38341dc0444.png)

I am getting this error even while specifying the version as '0.12.2'

**Comment by shripathee** [comment]
I just made it work temporarily by updating the node-webkit-builder version in package.json of the plugin to the latest version (1.0.8) and running 'npm install'.

**Comment by adam-lynch** [comment]
This should be sorted with the latest release (grunt-nw-builder@2.0.0)
